import React, { useEffect, useState } from 'react';
import styles from '../../styles/main/[menu]-styles.module.scss';
import { useRouter } from 'next/router'
import Bg from '../../components/Bg';
import { MarvelLogoSmall, MenuLink } from '../../styled-components/[menu]-sc';
import Link from 'next/link';
import CharsSection from '../../components/CharsSection';
import MoviesSection from '../../components/MoviesSection';
import HqsSection from '../../components/HqsSection';
import Head from 'next/head';

export default function Main(): JSX.Element {

  const { menu } = useRouter().query;

  const [selectedSection, setselectedSection] = useState<JSX.Element>();
  const [pageName, setpageName] = useState<string>('');

  useEffect(function () {
    switch (menu) {
      case 'chars': setselectedSection(<CharsSection />); setpageName(menu); break;
      case 'movies': setselectedSection(<MoviesSection />); setpageName(menu); break;
      case 'hqs': setselectedSection(<HqsSection />); setpageName(menu); break;
      default: setselectedSection(<CharsSection />); setpageName('chars'); break;
    }
  }, [menu])

  return (
    <>
      <Head>
        <title>{pageName && pageName[0]?.toUpperCase() + pageName?.slice(1) + ' - '}Mestres da Web dev challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bg />
      <div className={styles.container}>
        <div className={styles.menu_div}>
          <div className={styles.menu_div_col1}>
            <MarvelLogoSmall>
              <p>MARVEL</p>
            </MarvelLogoSmall>
          </div>
          <nav className={styles.menu_div_col2}>
            <MenuLink>
              <Link href="/main/chars?page=1"><p style={{ color: (menu !== 'chars' ? 'gray' : '') }}>Personagens</p></Link>
            </MenuLink>
            <MenuLink>
              <Link href="/main/movies?page=1"><p style={{ color: (menu !== 'movies' ? 'gray' : '') }}>Filmes</p></Link>
            </MenuLink>
            <MenuLink>
              <Link href="/main/hqs?page=1"><p style={{ color: (menu !== 'hqs' ? 'gray' : '') }}>HQs</p></Link>
            </MenuLink>
          </nav>
          <div className={styles.menu_div_col3}>
            <div>
              <img src='/imgs/avatar.png' alt="Avatar image"></img>
              <Link href="/login">Sair</Link>
            </div>
          </div>
        </div>
        {selectedSection}
      </div>
    </>
  )
}