import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { MarvelLogoRedDiv, MarvelLogoText } from '../styled-components';

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mestres da Web dev challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.gradient_effect}></div>
      
      <div className={styles.page_content_div}>
        <div className={styles.col1}>
          <MarvelLogo />
        </div>

        <div className={styles.col2}>

        </div>
      </div>

    </div>
  )
}

function MarvelLogo() {
  return (
    <div className={styles.marvel_logo}>
      <MarvelLogoRedDiv>
        <MarvelLogoText>MARVEL</MarvelLogoText>
      </MarvelLogoRedDiv>
    </div>
  )
}
